package io.github.altenhofen.openpixapi.qrcode;

import com.google.zxing.common.BitMatrix;
import java.awt.*;

/** Represents a image renderer for the QRCode */
public interface PixQrRenderer {
  /**
   * renders the pix into desired format
   *
   * @param matrix the bitmatrix generated by Zxing
   * @param config the configuration object for qrcode options
   * @return the pix into desired format
   * @throws Exception if rendering fails
   */
  PixQrOutput render(BitMatrix matrix, PixQrConfig config) throws Exception;
}
